import type { DealInputs, LenderSettings } from './types'

export const DEFAULT_LENDER_SETTINGS: LenderSettings = {
  hmlLenderName: 'lender LLC',
  hmlLeveragePP: 0.75,
  hmlLeverageRehab: 1.0,
  hmlMonthlyRate: 0.01,
  hmlAppraisalCost: 500,
  hmlUnderwritingFees: 800,
  hmlPointsPct: 0.01,
  hmlOtherFees: 2000,
  hmlExtraFees: 0,
  refiLenderName: 'ABC bank',
  refiAnnualRate: 0.07,
  refiAppraisalCost: 500,
  refiUnderwritingFees: 1200,
  refiPointsPct: 0.03,
  refiOtherFees: 3500,
  maxMoneyInDeal: 65000,
  minEquityPct: 0.20,
}

export const DEFAULT_DEAL_INPUTS: DealInputs = {
  address: '',
  seller: '',
  propertyType: 'SFR',
  sqft: 0,
  yearBuilt: 0,
  purchasePrice: 0,
  rehabEstimate: 0,
  changeOrders: 0,
  changeOrdersMode: 'percent',
  changeOrdersPct: 0.10,
  marketRent: 0,
  arv: 0,
  exitStrategy: 'rental',
  rehabMonthsManual: 0,
  closingCostsBuyOverride: -1,
  seasoningMonths: 4,
  propertyTaxMonthly: 125,
  propertyTaxMode: 'monthly',
  insuranceMonthly: 100,
  insuranceMode: 'monthly',
  hoaMonthly: 0,
  hoaMode: 'monthly',
  stateIncomeTaxMonthly: 0,
  stateTaxMode: 'monthly',
  mortgageIOMonthly: 0,
  pmMode: 'percent',
  pmRate: 0.10,
  pmFixed: 0,
  capexMode: 'percent',
  capexRate: 0.15,
  capexFixed: 0,
  customExpenses: [
    { id: 'ot_inspection', name: 'Inspection', amount: 550, frequency: 'one-time', funded: false },
    { id: 'ce_lawn', name: 'Lawn maintenance', amount: 80, frequency: 'monthly', funded: false },
  ],
  rehabCustomCosts: [
    { id: 'rc_cleanup', name: 'Clean Up', amount: 300, funded: false, isDefault: true },
    { id: 'rc_photographer', name: 'Photographer', amount: 180, funded: false, isDefault: true },
  ],
  hmlCustomFees: [],
  refiCustomFees: [],
  hmlLoanPP: 0,
  hmlLoanRehab: 0,
  refiLTVOverride: 0,
  refiTitleCostsOverride: 0,
  otherAdjustmentsAtClose: 0,
  locationScore: 0,
  comments: '',
}
